<a href="https://colab.research.google.com/github/davidjie1949/learnPytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

shift + enter = execute code;

ctrl + m + m = turn to text;

ctrl + m + y = turn to code;


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [2]:
!nvidia-smi

Tue May 21 08:12:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX.size

<function Tensor.size>

In [15]:
MATRIX[0].shape

torch.Size([2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9],
                        [10,11,12],
                        [13,14,15],
                        [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 6, 3])

In [19]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data <-> update random numbers

In [20]:
# Create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2524, 0.8590, 0.0343, 0.6220],
        [0.7702, 0.9172, 0.9317, 0.9410],
        [0.1598, 0.1393, 0.7156, 0.2787]])

In [21]:
random_tensor.ndim

2

In [22]:
# Creaet a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R,G,B)
random_image_size_tensor

tensor([[[0.8476, 0.6429, 0.8778],
         [0.9958, 0.4948, 0.4773],
         [0.4801, 0.7733, 0.4097],
         ...,
         [0.0193, 0.1681, 0.1085],
         [0.9313, 0.8039, 0.4727],
         [0.0952, 0.4799, 0.9144]],

        [[0.1204, 0.0532, 0.3208],
         [0.3809, 0.2879, 0.4084],
         [0.0450, 0.0152, 0.8366],
         ...,
         [0.5139, 0.7753, 0.6016],
         [0.2477, 0.7527, 0.3599],
         [0.6119, 0.9946, 0.7731]],

        [[0.5147, 0.7058, 0.4490],
         [0.9277, 0.3521, 0.5019],
         [0.4461, 0.4894, 0.2100],
         ...,
         [0.5046, 0.7080, 0.7386],
         [0.6453, 0.0192, 0.5189],
         [0.4025, 0.0754, 0.9298]],

        ...,

        [[0.2382, 0.5512, 0.1823],
         [0.5128, 0.6412, 0.7715],
         [0.9299, 0.7404, 0.9928],
         ...,
         [0.5213, 0.9080, 0.9292],
         [0.9383, 0.0934, 0.7938],
         [0.6341, 0.6722, 0.5514]],

        [[0.2071, 0.6687, 0.4632],
         [0.7357, 0.7287, 0.1202],
         [0.

In [23]:
random_image_size_tensor.size

<function Tensor.size>

In [24]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [25]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# use torch.range() and get deprecated msg, use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten_alt = torch.arange(start=1, step=100, end=1100)
one_to_ten_alt

tensor([   1,  101,  201,  301,  401,  501,  601,  701,  801,  901, 1001])

In [30]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [32]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32, device=None)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])


### gettin info from tensors

1. Tensor not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensor not right shape - to get shape from a tensor, can use tensor.shape
3. Tensor not on the right device - to get device from a tensor, can use tensor.device

In [36]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6007, 0.4171, 0.3226, 0.9662],
        [0.4666, 0.7189, 0.3129, 0.8020],
        [0.3037, 0.3488, 0.0658, 0.6953]])

In [37]:
# find out details about some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors(tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplicaton


In [38]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 100)

tensor([101, 102, 103])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. element-wise multiplication
2. matrix multiplication (dot product)

In [43]:
# element wise multi
tensor*tensor

tensor([1, 4, 9])

In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 675 µs, sys: 1.13 ms, total: 1.8 ms
Wall time: 7.66 ms


tensor(14)

In [45]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

In [46]:
torch.matmul(tensorA, tensorB)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [48]:
# transpose
tensorB.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [49]:
torch.matmul(tensorA, tensorB.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

### Finding the min, max, sum, mean, etc (tensor aggregation)


In [50]:
# create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [51]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
#find the mean, the torch.mean() fnc requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [55]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Find the position in tensor that has the min value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [57]:
x[0]

tensor(0)

In [58]:
# Find the position in tensor that has the maximum alue with argmax()
x.argmax()

tensor(9)

In [59]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tesnsors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (torch.vstack) or side by side (torch.hstack)
* Squeeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [7]:
# Let's create a tensor
import torch
x = torch.arange(1.0, 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [8]:
# add an extra dimension
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [9]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [10]:
# Change the view
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [11]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [12]:
Z = x.view(1,10)
Z, Z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [13]:
# changing z changes x (becuase a view of a tensor shares the same meory as the original input)
Z[:,0] = 5
Z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [14]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [15]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [18]:
# torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped = x_reshaped.reshape(1,10)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra diamentons from x_reshaped
x_sequeued = x_reshaped.squeeze()
print(f"New tenor: {x_sequeued}")
print(f"New shape: {x_sequeued.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
New tenor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [23]:
# torch.unsqueeze() - add a single dimension to a target tensor at s specific dim
x_unsequeezed = x_sequeued.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsequeezed}")
print(f"New shape: {x_unsequeezed.shape}")

x_unsequeezed = x_sequeued.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsequeezed}")
print(f"New shape: {x_unsequeezed.shape}")


New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])

New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [26]:
# torch.permute - rearranges the dimensions of a target tensor in a specificed order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"x_original shape: {x_original.shape}")
print(f"x_permuted shape: {x_permuted.shape}")
print(f"x_original shape: {x_original.shape}")


x_original shape: torch.Size([224, 224, 3])
x_permuted shape: torch.Size([3, 224, 224])
x_original shape: torch.Size([224, 224, 3])


## Indexing(selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [28]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [29]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [32]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [33]:
x[0][2][2]

tensor(9)

In [34]:
x[:, 0]

tensor([[1, 2, 3]])

In [35]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [36]:
x[:,1,1]

tensor([5])

In [40]:
 x[:,:,1]

tensor([[2, 5, 8]])

In [41]:
x[0,0,:]

tensor([1, 2, 3])